planner_configs:

  RRTConnect:
    type: geometric::RRTConnect
    range: 0.05        # 기본값보다 작게: 좁은 공간 대응
    goal_bias: 0.2     # 목표 근처를 더 자주 탐색
    intermediate_states: true

  BKPIECE:
    type: geometric::BKPIECE
    range: 0.05
    goal_bias: 0.2
    border_fraction: 0.9
    failed_expansion_score_factor: 0.4
    intermediate_states: true

  EST:
    type: geometric::EST
    range: 0.05
    goal_bias: 0.1
    min_valid_path_fraction: 0.9

default_planner_config: RRTConnect
