# gripper/controller_manager:
#   ros__parameters:
#     update_rate: 500  # Hz
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
#     robotiq_gripper_controller:
#       type: position_controllers/GripperActionController
#     robotiq_activation_controller:
#       type: robotiq_controllers/RobotiqActivationController

# robotiq_gripper_controller:
#   ros__parameters:
#     default: true
#     joint: robotiq_85_left_knuckle_joint
#     use_effort_interface: true
#     use_speed_interface: true

# robotiq_activation_controller:
#   ros__parameters:
#     default: true

gripper/controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint: robotiq_85_left_knuckle_joint
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
      default: true
      joint: robotiq_85_left_knuckle_joint
      use_effort_interface: true
      use_speed_interface: true
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController
      default: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


gripper/robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

# robotiq_activation_controller:
#   ros__parameters:
#     default: true

# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - robotiq_85_left_knuckle_joint
